apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: hello
spec:
  containers:
  - name: web
    image: hello-web:1.1
    ports:
    - containerPort: 80
    imagePullPolicy: IfNotPresent
